title: Los Santos
description: Este projeto é um website pessoal desenvolvido em HTML, CSS e JavaScript, criado para demonstrar minhas habilidades de front-end. 
source: ./docs
theme: jekyll-theme-primer
baseurl: ""
url: "https://LucasConradi.github.io/lossantos"