title: Los Santos
description: Este projeto é um website pessoal desenvolvido em HTML, CSS e JavaScript, criado para demonstrar minhas habilidades de front-end e apresentar meu portfólio acadêmico e profissional. 
url: "https://LucasConradi.github.io/LosSantos" 